language: ruby
rvm: 2.1.2
gemfile: Gemfile
env: DB=mysql MYSQL_HOST="127.0.0.1" MYSQL_PORT="3306" MYSQL_USER="root"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qq
  - sudo apt-get install python-software-properties
  - sudo echo | sudo add-apt-repository ppa:ondrej/php5;
  - sudo apt-get update -qq
  - sudo apt-get install curl php5 php5-cli php5-mysql
  - cd ./tests
  - sudo curl -sS https://getcomposer.org/installer | php"
install: ./install.sh
script: ./run.sh
