language: ruby
rvm:
  - 1.9.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get update -qq
  - sudo apt-get install python-software-properties
  - sudo echo | sudo add-apt-repository ppa:ondrej/php5;
  - sudo apt-get update -qq
  - sudo apt-get install curl mysql-server mysql-client php5
  - sudo curl -sS https://getcomposer.org/installer | php
env:
  - MYSQL_HOST=127.0.0.1 MYSQL_PORT=3306 MYSQL_USER=root
script: "bundle exec rspec spec"
